version: "3.9"
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/vector_db:/data

  app:
    build: .
    command: uvicorn rag_matmath.api.server:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - chroma
